### ISSUE TITLE
proto.Methods.Marshal/Unmarshal: function and variable redeclaration

### ISSUE THREAD

**Issue by fdymylja** [cosmos/cosmos-proto#29]
Marshal and Unmarshal fast methods produce some functions with constant names, ex: `skip`, `encodeVarint` and variables such as `ErrOverflow`.

This becomes problematic when `protoc`compiles two files because it will redeclare those functions and go code will not compile.

**Comment by fdymylja** [comment]
@technicallyty pinging you in case you want to handle this.

**Comment by technicallyty** [comment]
Yup, just tested this in standalone VTprotobuf test project. It also happens there. There's no duplicates if you run it in one fell swoop by passing in all the files at once, instead of looping over all the files and calling `protoc` individually on them

i'm not entirely sure what the best way to go about fixing this is, though here's one solution i can think of:

- make a temp file that tracks what packages already have a generated file in them as part of the protogen script
- - maybe not the most ideal as it requires a more robust script and overhead?

any other ideas?

**Comment by aaronc** [comment]
It's the same code always right? We should just make these library functions then - `github.com/cosmos/cosmos-proto/runtime` or something

**Comment by aaronc** [comment]
Awesome 👍

**Comment by fdymylja** [comment]
> It's the same code always right? We should just make these library functions then - `github.com/cosmos/cosmos-proto/runtime` or something

I think it's always the same code, I'm not sure if the choice to re-declare it in every package (which happens in gogoproto too) has something to do with inlining, I'm not familiar with go compiler semantics. It just seems weird that gogoproto implementers have decided to re-define it each time.
